name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run ESLint
        run: npm install eslint @eslint/js && npx eslint . --ext .js

      - name: Dependency audit
        run: npm audit --audit-level=high || true

  docker-build-scan:
    runs-on: ubuntu-latest
    needs: build-test-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t todos-service:${{ github.sha }} .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: todos-service:${{ github.sha }}
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
